export default {
	catch_error: "We faced some issues processing the data. Please try again."
}